version: '2.1'

services:
  deploy-docker:
    image: deploy-docker
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /usr/src/app/node_modules
      - .:/usr/src/app
    ports:
      - 3000:3000